#!/usr/bin/env bash
set -euo pipefail

err=0
rnd=$RANDOM

cd demo
for demo in *; do
  ret="$("./$demo" $rnd)" && [[ ret -eq rnd ]] &&
  echo -en '\e[32m✓' || { echo -en '\e[31m✗' && ((++err)); }
  echo -e "\e[00m $demo"
done

exit $err