#!/usr/bin/env sh
# $1 num; $2 .blend
''''exec blender --factory-startup -b ${2:+"$2"} -P "$0" -- "$@" #'''
import sys; print(sys.argv[sys.argv.index('--') + 1])

# disable unsuppressable output for test
import os; sys.stdout.flush(); o = os.dup(1); os.close(1)