#!/bin/sh
f() {
  tmp="$(mktemp)" &&
  gcc -ansi -pedantic -Wall -Wextra -Wconversion -Werror -o"$tmp" -xc - &&
  "$tmp" "$@"
  ret=$?
  rm "$tmp"
  return $ret
}

f "$@" << 'eof'

#include <stdio.h>

int main(int argc, char** argv) {
  if (argc < 2) { return 1; }
  return printf("%s\n", argv[1]) > 0 ? 0 : 1;
}